### ISSUE TITLE
AssertionError: not application/protobuf response

### ISSUE THREAD

**Issue by falegre05** [dweinstein/node-google-play-cli#9]
Hi, I've been using this api for a while and all was working great having all my apks updated and suddenly today it stopped working. When I try to use the command gp-download, gp-download-meta or some others it fails saying "AssertionError [ERR_ASSERTION]: not application/protobuf response". However, I can still use gp-bulk-details, gp-search or gp-get-token. 
By removing the .toString() of the err.toString() from the download-meta file, I can get a little more explanatory error message: 

`_$ gp-download-meta com.twitter.android
{ AssertionError [ERR_ASSERTION]: not application/protobuf response
    at /usr/local/lib/node_modules/google-play-cli/node_modules/gpapi/lib/api.js:245:9
    at tryCatcher (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise.js:638:18)    at PromiseArray._resolve (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/promise.js:638:18)    at Request._callback (/usr/local/lib/node_modules/google-play-cli/node_modules/bluebird/js/release/nodeback.js:45:21)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }_`

This is reproducible by any apk i've tried. Hope you can help me or at least tell me what have happened. Is it possible that Google has changed its API or something like that??

Thank you very much for your work.

**Comment by falegre05** [comment]
I've been doing some research about this error. Activating the debug, it seemed to me that the problem could be related to Google changing the header field _'content-type'_ from _'application/protobuf'_ to _'application/binary'_ or something similar given that the statusCode was 200. So I commented the assert:
 _'assert(res.headers['content-type'] === 'application/protobuf', 'not application/protobuf response');'_ in the api.js file from the gpapi lib wich was throwing the error.
The result of this change is that now gp-download-meta and gp-download-info runs perfectly again, but when I try to make an actual download with gp-download, I get the following error: 
_RequestError: Error retrieving information from server. [DF-DFERH-01]_

**Comment by dweinstein** [comment]
thanks for the report...

commenting out the assert did seem to help me, are you sure that the app you're trying to download is compatible with the profile you're using?

try downloading a few other apps, do those work at all?

I might make a release with the assert removed...

**Comment by dweinstein** [comment]
there's a prerelease 4.5.1-0 that uses the gpapi version without the assert. Give that a shot.

**Comment by falegre05** [comment]
Thank you for your fast answer. Finally I've realized that I was writting _'gp-download com.twitter.android twitter.apk'_ without the ">" symbol, so that's what I was getting a RequestError. Commenting out the assert seems to resolve the whole problem. I hope it is for good.

Again, thanks for your work and fast answer :)

**Comment by Laksh47** [comment]
Google changed the header field 'content-type' from 'application/protobuf' to 'application/binary'

Will this be fixed ? @dweinstein

**Comment by dweinstein** [comment]
The assert was removed in the current release
